# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 357)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.InputBox = QtWidgets.QGroupBox(self.centralWidget)
        self.InputBox.setObjectName("InputBox")
        self.gridLayout = QtWidgets.QGridLayout(self.InputBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.InputBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.InputBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 9, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.InputBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.filename = QtWidgets.QLineEdit(self.InputBox)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.InputBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.urlInput = QtWidgets.QLineEdit(self.InputBox)
        self.urlInput.setObjectName("urlInput")
        self.gridLayout.addWidget(self.urlInput, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.InputBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.directory = QtWidgets.QLineEdit(self.InputBox)
        self.directory.setObjectName("directory")
        self.gridLayout.addWidget(self.directory, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.InputBox, 0, 0, 1, 1)
        self.finished = QtWidgets.QLabel(self.centralWidget)
        self.finished.setText("")
        self.finished.setObjectName("finished")
        self.gridLayout_2.addWidget(self.finished, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 835, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuTwitter_Crawler = QtWidgets.QMenu(self.menuBar)
        self.menuTwitter_Crawler.setObjectName("menuTwitter_Crawler")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionStart_crawling = QtWidgets.QAction(MainWindow)
        self.actionStart_crawling.setObjectName("actionStart_crawling")
        self.actionStop_crawling = QtWidgets.QAction(MainWindow)
        self.actionStop_crawling.setObjectName("actionStop_crawling")
        self.actionClose_Program = QtWidgets.QAction(MainWindow)
        self.actionClose_Program.setObjectName("actionClose_Program")
        self.menuTwitter_Crawler.addAction(self.actionStart_crawling)
        self.menuTwitter_Crawler.addAction(self.actionClose_Program)
        self.menuBar.addAction(self.menuTwitter_Crawler.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputBox.setTitle(_translate("MainWindow", "Please Enter Information for Crawling"))
        self.label_2.setText(_translate("MainWindow", "Welcome to the TwitterCrawler! The Crawler will get the 20 latest tweets from any given Twitter account and save them into a  .csv file."))
        self.pushButton.setText(_translate("MainWindow", "Crawl Babyl!"))
        self.label.setText(_translate("MainWindow", "Twitter-URL (format: \"https://twitter.com/realDonaldTrump\"):"))
        self.label_4.setText(_translate("MainWindow", "Name of file: (format: \"superduperfile\")"))
        self.label_3.setText(_translate("MainWindow", "Safe tweets to directoy: (format: \"C:/hello\")"))
        self.menuTwitter_Crawler.setTitle(_translate("MainWindow", "Twitter Crawler"))
        self.actionStart_crawling.setText(_translate("MainWindow", "Start crawling"))
        self.actionStop_crawling.setText(_translate("MainWindow", "Stop crawling"))
        self.actionClose_Program.setText(_translate("MainWindow", "Close Program"))

